name: ut_nguyen_mobile
description: Mobile app v2 for emergency voice calling with Flutter, Flask and ZEGOCLOUD.
publish_to: "none"

version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  provider: any
  shared_preferences: any
  dio: any
  dio_cookie_manager: any
  cookie_jar: any
  path_provider: any
  speech_to_text: any
  flutter_tts: any
  flutter_ringtone_player: any
  firebase_core: any
  firebase_messaging: any
  zego_uikit_prebuilt_call: any
  zego_uikit_signaling_plugin: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

dependency_overrides:
  floating:
    path: vendor/floating
  flutter_ringtone_player:
    path: vendor/flutter_ringtone_player

flutter:
  uses-material-design: true

